### ISSUE TITLE
`thirdparty/apple/dnsinfo.h` is missing in release archive

### ISSUE THREAD

**Issue by xhochy** [c-ares/c-ares#764] opened 2024-05-24 14:32 UTC
The archive hosted at `https://c-ares.haxx.se/download/c-ares-{{ version }}.tar.gz` doesn't include the above mentioned header.

**Comment by bagder** [comment] 2024-05-24 15:15
Duplicate of #763

**Comment by bagder** [comment] 2024-05-24 15:17
Fixed in git already

**Closed by bagder** 2024-05-24 15:17 UTC
