### ISSUE TITLE
Fail to resolve after DNS server dies and another server starts

### ISSUE THREAD

**Issue by apolukhin** [c-ares/c-ares#652] opened 2023-12-08 11:33 UTC
After upgrade from 1.20.1 to 1.22.1 we are noticing failures in test that checks switching from a dead DNS server to an alive one.

The test:
0) Sets the following c-ares options https://github.com/userver-framework/userver/blob/00d7a3ddf31c318a92fde08f19f4d8c5159a7e48/core/src/clients/dns/net_resolver.cpp#L179-L192
1) Calls `ares_set_servers_ports_csv` with [::1]:3000 and [::1]:3001
2) Start DNS server at `[::1]:3000` (DNS server at `[::1]:3001` is not started!)
3) Resolve some hosts via c-ares
4) Kill DNS server at `[::1]:3000` and start a new DNS server at `[::1]:3001`
5) Resolve a host
6) Kill DNS server at `[::1]:3001` and start a DNS server at `[::1]:3000`
7) Attempt to resolve a host times out (timeout=15 seconds). However the DNS server at `[::1]:3000` was requested by c-ares and the DNS server **successfully** responded in the same second it was requested

**Comment by bradh352** [comment] 2023-12-08 11:42
Have you tried the patch from #651 ?

**Comment by bradh352** [comment] 2023-12-08 13:14
What is query_timeout.count() and query_attempts ?

What happens if you don't set ARES_FLAG_STAYOPEN ?

Are you waiting for #7 before attempting #8?  Or are these in parallel?  Immediate timeout usually means that the query hit its max tries, usually because creation of the socket to all dns servers failed.

**Comment by apolukhin** [comment] 2023-12-08 13:32
> What is query_timeout.count() and query_attempts ?

query_timeout is 15 seconds (query_timeout.count() is 15000); query_attempts is 1

> What happens if you don't set ARES_FLAG_STAYOPEN ?

Does not seem to change anything

> Are you waiting for 7 before attempting 8?

Yes, they happen one after another, sequentially

**Comment by bradh352** [comment] 2023-12-08 13:58
That query timeout is way too long, as that's a per-attempt timeout.  The default is 2s, which even that is an eternity in modern networks.

what happens if you set attempts > 1? 

I just committed an enhanced test case trying to reproduce some similar scenario and it appears to work fine:
https://github.com/c-ares/c-ares/commit/1edaa44

Have you actually tried the latest c-ares main to make sure it wasn't some interaction with some other bug already resolved?

**Comment by bradh352** [comment] 2023-12-08 14:15
also, if you could isolate a test case in your system that mostly is hitting c-ares and share an strace() that could be helpful in seeing what is going on, if there are any system errors in socket(), connect(), send(), recv() etc.  A tcpdump would probably also be useful.  At least with the current c-ares main I can't seem to reproduce anything.

**Comment by apolukhin** [comment] 2023-12-08 14:21
> what happens if you set attempts > 1?

Same problem with attempts == 3

> That query timeout is way too long, as that's a per-attempt timeout. The default is 2s, which even that is an eternity in modern networks.

Setting the timeout to 2s does not help.

However, setting the timeout to 2s and attempts == 3 helps. Alas, in that case only one of two IP addresses is returned (1.20.1 returns 2 addresses and work with 15 seconds timeout and 1 attempt).

> Have you actually tried the latest c-ares main to make sure it wasn't some interaction with some other bug already resolved?

Will try to do that in a few hours

**Comment by apolukhin** [comment] 2023-12-09 08:10
> Have you actually tried the latest c-ares main to make sure it wasn't some interaction with some other bug already resolved?

Tests keep failing even on new version :(

> isolate a test case in your system that mostly is hitting c-ares and share an strace()

We'll do that at Monday

**Comment by bradh352** [comment] 2023-12-09 18:36
Please make sure your test case isn't making any assumptions about the order of server tries or something as the behavior has definitely changed in c-ares.  Prior versions would always try the first configured server for every query, current versions isolate bad servers and re-sort them based on failures.

Also, if you can share how you're testing or a specific test case I might be able to take a look at it.

**Comment by apolukhin** [comment] 2023-12-11 15:46
While taking a closer look at the new `ServerNoResponseFailover` test from https://github.com/c-ares/c-ares/commit/a47b352 I've noted a difference with our tests. `ServerNoResponseFailover` just gives an empty response, while we are actually shutting down the server and closing the socket.

I've added a test `ServerDisconnectFailover` https://pastebin.com/dJX5a07K , expecting that it would work close to the `ServerNoResponseFailover`

However, it failed in multiple places: https://pastebin.com/DURV8FSG

There are some quite suspicious failures: 
```
Actual function call count doesn't match EXPECT_CALL(*servers_[2], OnRequest("www.example.com", ns_t_a))...
         Expected: to be called 3 times
           Actual: never called - unsatisfied and active
```
Please, take a look... Is that behavior expected?

**Comment by bradh352** [comment] 2023-12-11 17:26
UDP is connectionless, so you changing that to a "Disconnect" will simply invalidate the file descriptor for listening on that port any more (remote won't be notified), but it would also have the side effect that it won't re-activate so any future routed requests will be lost, nothing will re-activate to obtain more requests.

I think sending "nothing" will not actually enqueue a response, but I may be wrong there and need to look at the code since UDP technically allows 0-byte packets ... tcp does not of course.  That said, a 0-byte UDP reply packet will just be consumed and ignored by c-ares, it wouldn't be associated with any particular request at all since multiple could be outstanding and it wouldn't know what to associate it with ... so even if it did send a 0-byte request c-ares internally would treat it as a no-response.

Obviously if you're forcing TCP or something, behavior could be different.

**Comment by bradh352** [comment] 2023-12-11 17:32
I've confirmed what I said is accurate, the mock server doesn't send anything at all, it acts like a lost packet which is normal for UDP since its connectionless:
https://github.com/c-ares/c-ares/blob/main/test/ares-test.cc#L422

You can see this too when running `./bin/arestest -v --gtest_filter=*ServerNoResponseFailover*`, note the missing "sending reply" for the requests that are dropped:
```
[ RUN      ] TransportModes/NoRotateMultiMockTest.ServerNoResponseFailover/0
Configured IPv4 mock server with TCP socket 3 on port 50507 and UDP socket 4 on port 60081
Configured IPv4 mock server with TCP socket 5 on port 50508 and UDP socket 6 on port 57182
Configured IPv4 mock server with TCP socket 7 on port 50509 and UDP socket 8 on port 56648
Configured library with servers:127.0.0.1:60081,127.0.0.1:57182,127.0.0.1:56648
received UDP request REQ QRY RD  Q:{'www.example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 60081
ProcessRequest(56206, 'www.example.com', A)
sending reply RSP QRY AA NOERROR Q:{'www.example.com' IN A} A:{'www.example.com' IN A TTL=100 2.3.4.5} on port 60081
HostCallback({ARES_SUCCESS {'www.example.com' aliases=[] addrs=[2.3.4.5]}})
received UDP request REQ QRY RD  Q:{'www.example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 60081
ProcessRequest(52222, 'www.example.com', A)
received UDP request REQ QRY RD  Q:{'www.example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 57182
ProcessRequest(52222, 'www.example.com', A)
received UDP request REQ QRY RD  Q:{'www.example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 56648
ProcessRequest(52222, 'www.example.com', A)
sending reply RSP QRY AA NOERROR Q:{'www.example.com' IN A} A:{'www.example.com' IN A TTL=100 2.3.4.5} on port 56648
HostCallback({ARES_SUCCESS {'www.example.com' aliases=[] addrs=[2.3.4.5]}})
received UDP request REQ QRY RD  Q:{'www.example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 56648
ProcessRequest(19226, 'www.example.com', A)
sending reply RSP QRY AA NOERROR Q:{'www.example.com' IN A} A:{'www.example.com' IN A TTL=100 2.3.4.5} on port 56648
HostCallback({ARES_SUCCESS {'www.example.com' aliases=[] addrs=[2.3.4.5]}})
received UDP request REQ QRY RD  Q:{'www.example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 56648
ProcessRequest(32658, 'www.example.com', A)
received UDP request REQ QRY RD  Q:{'www.example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 60081
ProcessRequest(32658, 'www.example.com', A)
sending reply RSP QRY AA NOERROR Q:{'www.example.com' IN A} A:{'www.example.com' IN A TTL=100 2.3.4.5} on port 60081
HostCallback({ARES_SUCCESS {'www.example.com' aliases=[] addrs=[2.3.4.5]}})
```

**Comment by bradh352** [comment] 2023-12-11 18:36
FYI, we have a release prepped for c-ares 1.24.0 that we'd like to get out the door.  I'd like to hold the release up to a couple of days to figure this issue out, however.  So as much information you can provide would be appreciated so we can get to the bottom of this.

**Comment by apolukhin** [comment] 2023-12-13 09:58
Our tests are too high-level, so I just reproduced the main parts of the tests logic with the whole set of our flags in https://github.com/c-ares/c-ares/pull/658

Looks that everything is fine (probably the errors are somewhere on our side in tests logic). No need to hold the release of 1.24.0, and this issue could be closed/

Could you please take a look at https://github.com/c-ares/c-ares/pull/658? I'd appreciate if it could be merged after some review, so that we'd be sure that failover is fine for async resolving

**Comment by bradh352** [comment] 2024-01-10 13:25
closing since this appears to work as expected

**Closed by bradh352** 2024-01-10 13:25 UTC
