### ISSUE TITLE
Server list order reset

### ISSUE THREAD

**Issue by nUl1** [c-ares/c-ares#717] opened 2024-02-24 17:38 UTC
Previously #594 introduced a dynamic server list ordering based on the number of consecutive failures. 
It works great in cases where all servers in the list are interchangeable but issues might emerge when this list was originally ordered with server priorities in mind (e.g. primary server followed by a backup one).

Currently there seems to be no clear way to bring a server back up in the list. Options I see are: 
 * Fail enough queries at all other servers to make a query go to this one;
 * Do a server list update that removes this server then reintroduce it with a second update;
 * Create a new channel and retire the old one.

Maybe a flag can be added to the CSV representation that will force failure count reset in `servers_update`? Or a method that replaces the whole list? Or did I miss some obvious solution to this problem?

**Comment by bradh352** [comment] 2024-02-24 23:43
Out of curiosity, is there a particular purpose to defining a primary vs backup?  I've never found a *legitimate* purpose for such a thing where there wasn't a better solution for the actual problem.  But if the ordering really does matter, then we'd probably want to set a timer (not sure what the default should be, 5mins?) to invalidate the failure count and resort the server list upon expiration of this timer to possibly restore the original ordering.  It wouldn't be *that* difficult to do if there is a real reason to do so.

**Comment by nUl1** [comment] 2024-02-25 08:54
> Out of curiosity, is there a particular purpose to defining a primary vs backup?
Most of the cases I've seen were various caching servers. Basically distibuting the server load with smaller instances and reducing latency/network traffic.

> we'd probably want to set a timer [...] to invalidate the failure count
That's exactly what I implemented application-side before finding out that `set_servers` does not affect the order for existing entries.

**Comment by bradh352** [comment] 2024-02-25 14:28
ok, so really just for load balancing reasons.  I can look at implementing this internally after I finish rewriting the last config parser using the new memory-safe parsing routines.  There's no good way to do it externally without killing in-flight queries.

That said, for load reduction, you should look at enabling the query cache in c-ares.  Most apps tend to look up the same few domains over and over and the built-in query cache in c-ares uses the advertised TTLs to properly cache just like the upstream DNS server would but locally (so lowest latency possible and no load to the upstream servers).

**Comment by bradh352** [comment] 2024-02-25 19:59
You can change the server list no problem without affecting inflight queries, they'll just be requeued.  The problem is if you clear the server list, then repopulate the server list, all queries will be killed upon clearing the list.  And as you've noticed, if you repopulate the server list with the same list of existing servers, it will not re-order them to the order you provided due to failure counts.

**Comment by bradh352** [comment] 2024-04-14 20:31
fixed in #731

**Closed by bradh352** 2024-04-14 20:31 UTC
