### ISSUE TITLE
1.17.0: missing cmake files in dist tar ball

### ISSUE THREAD

**Issue by kloczek** [c-ares/c-ares#375] opened 2020-11-18 02:13 UTC
cmake fails with:
```
-- Looking for __system_property_get - not found
CMake Error: File /home/tkloczko/rpmbuild/BUILD/c-ares-1.17.0/c-ares-config.cmake.in does not exist.
CMake Error at /usr/share/cmake/Modules/CMakePackageConfigHelpers.cmake:330 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:606 (CONFIGURE_PACKAGE_CONFIG_FILE)
```

It would be as well good to change tagging convention because current one does not allow use tagged tar balls because tags does not contain just `version` with only dots.
Current tagging convention is causing that https://github.com/c-ares/c-ares/archive/c-ares-1_17_0.tar.gz tar ball has as base directory `c-ares-c-ares-1_17_0/`

**Comment by bradh352** [comment] 2020-11-18 02:25
dupe of #373

**Closed by bradh352** 2020-11-18 02:25 UTC

**Comment by kloczek** [comment] 2020-11-18 02:35
What about considering change tagging convention on next release? :)

**Comment by bradh352** [comment] 2020-11-18 02:53
Can you clarify your suggestion?  It isn't clear what you are saying.

**Comment by kloczek** [comment] 2020-11-18 03:14
With using just `version` like `1.17.0' as tag string it is:
- easier to switch between dist ad tagged tar balls
- easier to detect new version (as there is no needs to use any per project regexp actual versions from git tags).

Easy availability of tagged tar balls is important ad only those tar balls gives you 100% guarantee that it will be possible to apply git patches from commits in git repo added after release so it allows as well easier wide testing git project against any distro on each git repo commit.

In case of using cmake or meson as build framework tagged tar ball can be straight used to build package in case or using ac/am/lt only command which is necessary to execute before `./configure` is `autoreconf -fiv` so it makes more and more sense to use tagged tar balls instead maintainer dist tar balls. It makes as well you tasks easier as all what you need to make new release is just add new version tag in git repo.

For example in my set of ~2.4k packages I have now:
```
[tkloczko@barrel SPECS]$ grep "Source0: %{VCS}/archive/" * | wc -l
403
```
So I've already managed to switch my rpm build procedures to use straight gitlab/github tagged tar balls in case of almost 20% of those packages.

**Comment by bradh352** [comment] 2020-11-18 12:18
I could get behind that kind of change.  The maintainer / make dist has caused lots of headaches.  @bagder thoughts?
