### ISSUE TITLE
cares would not use the second dns when the first dns return F.ROOT-SERVER.NET

### ISSUE THREAD

**Issue by llluiop** [c-ares/c-ares#226] opened 2018-10-10 09:05 UTC
I have two dns server set, the first is 10.201.128.1, second is 8.8.8.8, the first dnsserver just return top root server see wireshark:
![2](https://user-images.githubusercontent.com/7302292/46725233-59563d80-ccae-11e8-9f60-1fd82a4b64f0.jpg)
![1](https://user-images.githubusercontent.com/7302292/46725234-59563d80-ccae-11e8-8fa0-205d1170cfd0.jpg)

in this situation, i can get the right address  and cares would not use the second dns to resolving, i have debug the source code in 1.14,it did so.

can you fix the issue please.

**Comment by bradh352** [comment] 2018-10-10 13:09
1) Is this a regression from a prior c-ares version?  If so, what version did it work correctly on and what version are you testing on (e.g. official 1.14.0 release, git master, etc)?
2) Does this work as you'd expect with some other DNS resolver? If so, which one?

**Comment by llluiop** [comment] 2018-10-11 02:06
1.it is not a regression , i have tested on 1.14, 1.13 and master
2.it would work when i use libcurl default dns resolver, see below, you can see it would use the second dns server:
![3](https://user-images.githubusercontent.com/7302292/46776107-bac4ed80-cd3c-11e8-9a04-a477cad3e4e1.jpg)

3.you can simulate the situation by adding this code in ares_parse_a_reply.c:
`int ares_parse_a_reply(const unsigned char *abuf, int alen,
                       struct hostent **host,
                       struct ares_addrttl *addrttls, int *naddrttls)
{
  char* a = abuf;
  a[7] = 0; //set Answer RRs to 0
  unsigned int qdcount, ancount;`

it will set "Answer RRs" to 0, then you can see this issue

**Comment by llluiop** [comment] 2018-10-15 08:57
@bradh352 hi，can you help me with this issue ,thanks a lot

**Comment by bradh352** [comment] 2021-11-15 13:23
Is this still present?  I'm pretty sure based on the description of this issue, it was recently resolved.  c-ares would previously stop on ARES_ENODATA on search, but now will continue.  Its possible there is another area that needs a bypass however.

**Comment by bradh352** [comment] 2023-01-28 15:16
closing due to lack of reply, assuming bug is fixed

**Closed by bradh352** 2023-01-28 15:16 UTC
Labels: Research Needed, Not Yet Confirmed
