### ISSUE TITLE
iOS build via CMake, error configure 

### ISSUE THREAD

**Issue by vintonliu** [c-ares/c-ares#377] opened 2020-11-18 09:27 UTC
cmake build with this ios [toolchain](https://github.com/leetal/ios-cmake)
 **CMAKE CONFIG:**
```
PLATFORM_CONFIG="-DCMAKE_TOOLCHAIN_FILE=./cmake/ios.toolchain.cmake \
               -DCMAKE_BUILD_TYPE=Debug \
               -DENABLE_BITCODE=0 \
               -DENABLE_ARC=0 \
               -DDEPLOYMENT_TARGET=9.0"

CMAKE_CONFIG="$PLATFORM_CONFIG \
                    -DCARES_STATIC=True \
                    -DCARES_STATIC_PIC=True \
                    -DCARES_SHARED=False \
                    -DCARES_BUILD_TOOLS=False \
                    -DCARES_BUILD_TESTS=False \
                    -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR/OS"

cmake -G"Ninja" $CMAKE_CONFIG -DPLATFORM=OS ./ || exit 1
ninja -j8 install || exit 1
```

**Problem:**
when configure: the func res_servicename was found but HAVE_RES_SERVICENAME_IN_LIBRESOLV=FALSE which 
cause CARES_USE_LIBRESOLV marco not been defined. Finally, when run on ios, I got error 11 on callback.

**Comment by bradh352** [comment] 2020-11-18 12:21
what version of c-ares?

**Comment by bradh352** [comment] 2020-11-18 12:57
also, is this a regression from a prior version?

**Comment by vintonliu** [comment] 2020-11-19 08:32
my c-ares version is 1.16.1.

**Comment by bradh352** [comment] 2020-11-19 12:23
any chance you could test with c-ares master?  And can you provide the entire output of the cmake process?

**Comment by bradh352** [comment] 2020-11-19 13:22
I added an iOS CMake target with #378 to our autobuild tests.  I seemed to work fine there and does show res_servicename in libresolv.

Travis output should be here after the PR merge is done building:
https://travis-ci.org/github/c-ares/c-ares/jobs/744651531

**Comment by bradh352** [comment] 2020-11-19 20:16
I'm going to assume either this was fixed in a later release, or its an issue with your use of the toolchain file.  You can reference the travis build script to see how we're building.

**Closed by bradh352** 2020-11-19 20:16 UTC

**Comment by vintonliu** [comment] 2020-11-20 08:15
Thanks for your help. 

I have read the .travis.yml, not found any special config difference with my toolchain. So I try to add 
-DCMAKE_C_FLAGS="-DCARES_USE_LIBRESOLV" at my CMAKE_CONFIG to force use LIBRESOLV, and it works fine.

Below is my config output, the same as checkout to master branch on my toolchain:
```
-- Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- Using NON-strict compiler checks by default. ENABLE_STRICT_TRY_COMPILE not provided!
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Configuring iphoneos build for platform: OS, architecture(s): armv7;armv7s;arm64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk
-- Using minimum deployment version: 10.0 (SDK version: 13.7)
-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- Using a data_ptr size of: 8
-- Using install_name_tool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool
-- Disabling bitcode support.
-- Disabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- Looking for res_servicename
-- Looking for res_servicename - found
-- Performing Test IOS_V10
-- Performing Test IOS_V10 - Success
-- Performing Test MACOS_V1012
-- Performing Test MACOS_V1012 - Failed
-- Looking for gethostbyname
```

**Comment by bradh352** [comment] 2020-11-20 11:28
That is definitely different looking output than you can see on travis: https://travis-ci.com/github/c-ares/c-ares/jobs/443922423

My guess is that you have pre-defined CMAKE_REQUIRED_LIBRARIES to include libresolv .... which is the only thing that would explain that behavior since it calls CheckFunctionExists() prior to CheckLibraryExists() and it assumes someone hasn't manipulated CMAKE_REQUIRED_LIBRARIES before such a check.
