### ISSUE TITLE
ares_gethostbyname resolving "localhost" on Windows

### ISSUE THREAD

**Issue by ChristianAmmer** [c-ares/c-ares#100] opened 2017-05-02 08:49 UTC
Resolving the hostname "localhost" should not involve DNS servers. Calling the windows API function `gethostbyname` with "localhost" does not create any UDP packets (it is also possible to turn-off/disable the Ethernet Adapter and `gethostbyname` with "localhost" still returns 127.0.0.1).
I did not found a documentation for the special handling of "localhost" but maybe the behavior for this part is similar to Windows `getaddrinfo` where the documentation says:

> If the pNodeName parameter points to a string equal to "localhost", all loopback addresses on the local computer are returned. 

Calling `ares_gethostbyname` on the other hand (e.g. ahost -t a localhost.) creates UDP packets. This is especially a problem if Issue #53 gets implemented which would lead to many DNS requests:

- localhost.first.parameterized.suffix.com
- localhost.second.parameterized.suffix.com
- localhost.third.parameterized.suffix.com
- ...
- localhost.

**Comment by bradh352** [comment] 2017-05-06 10:54
Issue #85 appears to be a duplicate of this

**Comment by bradh352** [comment] 2018-02-08 23:22
closed as duplicate

**Closed by bradh352** 2018-02-08 23:22 UTC
