### ISSUE TITLE
c-ares 1.31.0 fails to resolve not fully qualified domains, but ok in c-ares 1.30.0

### ISSUE THREAD

**Issue by egtvedt** [c-ares/c-ares#852] opened 2024-08-04 11:11 UTC
I suspect commit https://github.com/c-ares/c-ares/commit/4248c642d2bc64ea500b525ebcd6ccfe2960c267 introduced a regression in c-ares regarding resolving not fully qualified domains.

Has there been any changes in this area after c-ares 1.31.0?

I can't reproduce this locally currently, will try to get that done next week.

**Comment by bradh352** [comment] 2024-08-04 12:19
Do you have any more information, or an example of what you're referring to?  Are you saying searching is broken?

Honoring `ndots: 0` in `resolv.conf` was a behavioral change for 1.31.0, which would alter search behavior.

I honestly doubt query cache would be involved in this, its hooked in at a very low level where all it does is echo back the same dns response that it would have received from the upstream server, but fed out of cache, to the caller (caller in this case being `ares_search()` or `ares_getaddrinfo()` depending on what api you are using). So if search was broken, it would also be broken without cache.

**Comment by egtvedt** [comment] 2024-08-04 12:37
Important piece I left out, the usage of c-ares is through curl, and in the specific failure it is due to a local proxy configured with a non fully qualified domain.

I'll try to get more info next week, ideally see if I can reproduce it with less complex setup/code.

**Comment by bradh352** [comment] 2024-08-04 14:32
Looks like we didn't have a specific test case to cover this, so I just added one in #853.  That said, it passes as expected so I really don't think whatever your issue is has anything to do with caching.

Also, there should be an 'ahost' utility installed with c-ares, you can use that instead of curl as a test as well.

**Comment by bradh352** [comment] 2024-08-14 18:16
any update on this? We'd need at least a full description of the issue, as previously discussed I added a test case for what I thought you said the issue was and it didn't show any issues.

**Comment by egtvedt** [comment] 2024-08-16 21:34
> any update on this? We'd need at least a full description of the issue, as previously discussed I added a test case for what I thought you said the issue was and it didn't show any issues.

I'm sorry I haven't been able to follow up.

Trying to reproduce locally has not been successfully yet, I need to understand more of what happens at the system that fails to behave as before.

Please keep low priority, I'll update once I understand more.

**Comment by mikaellindemann** [comment] 2024-08-19 12:10
We started receiving the following error looking up domains that are only available inside our Tailscale VPN, when upgrading c-ares from 1.28.1 to 1.33.0. We use c-ares through the gRPC C++ library.

```
DNS resolution failed for portfolio-service:5060: C-ares status is not ARES_SUCCESS qtype=A name=portfolio-service is_balancer=0: DNS server returned general failure.
```

Here `portfolio-service` is a subdomain to our VPN search-domain `tailXXXXX.ts.net`.

When we downgrade to 1.28.1, it can resolve our domain again.

**Comment by bradh352** [comment] 2024-08-19 14:43
Can you describe your setup a bit more ?  What OS is this on?  Are you trying to do some sort of split-dns?  Can you share your DNS configuration?  Can you try resolving the same domain with the `ahost` utility?

**Comment by mikaellindemann** [comment] 2024-08-21 07:15
1. Linux Ubuntu 22.04 - also, we consume gRPC and c-ares through vcpkg.
2. Yes, VPN domains only available through the VPN - the VPN client sets up /etc/resolv.conf such that the search domain is available. I'm unsure how it configures the DNS IP's and if we are using a forwarding VPN DNS. I will investigate this.
3. I'm unsure what configuration I should print here. We use the normal DNS setup in AWS, and then what the Tailscale client sets up on top. I will share our `/etc/resolv.conf` in the bottom of this comment and the output of `resolvectl status`.
4. I'm not sure the utility is built through vcpkg - will look around if the other answers does not point to something good.
5. Yes - specifying `portfolio-service.tailXXXXX.ts.net` in our gRPC client works without issues.
6. Since we consume through vcpkg, and not all versions have been released there, I will only have these options available: https://vcpkg.link/ports/c-ares/versions - I will check if the issue happens in 1.31.0 as well.

```
# /etc/resolv.conf

nameserver 127.0.0.53
options edns0 trust-ad
search eu-central-1.compute.internal tailXXXXX.ts.net
```

```bash
$ resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (ens5)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 172.31.0.2
       DNS Servers: 172.31.0.2
        DNS Domain: eu-central-1.compute.internal

Link 3 (tailscale0)
    Current Scopes: DNS
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 100.100.100.100
       DNS Servers: 100.100.100.100
        DNS Domain: tailXXXXX.ts.net ~0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa ~100.100.in-addr.arpa ~101.100.in-addr.arpa
                    ~102.100.in-addr.arpa ~103.100.in-addr.arpa ~104.100.in-addr.arpa ~105.100.in-addr.arpa
                    ~106.100.in-addr.arpa ~107.100.in-addr.arpa ~108.100.in-addr.arpa ~109.100.in-addr.arpa
                    ~110.100.in-addr.arpa ~111.100.in-addr.arpa ~112.100.in-addr.arpa ~113.100.in-addr.arpa
                    ~114.100.in-addr.arpa ~115.100.in-addr.arpa ~116.100.in-addr.arpa ~117.100.in-addr.arpa
                    ~118.100.in-addr.arpa ~119.100.in-addr.arpa ~120.100.in-addr.arpa ~121.100.in-addr.arpa
                    ~122.100.in-addr.arpa ~123.100.in-addr.arpa ~124.100.in-addr.arpa ~125.100.in-addr.arpa
                    ~126.100.in-addr.arpa ~127.100.in-addr.arpa ~64.100.in-addr.arpa ~65.100.in-addr.arpa ~66.100.in-addr.arpa
                    ~67.100.in-addr.arpa ~68.100.in-addr.arpa ~69.100.in-addr.arpa ~70.100.in-addr.arpa ~71.100.in-addr.arpa
                    ~72.100.in-addr.arpa ~73.100.in-addr.arpa ~74.100.in-addr.arpa ~75.100.in-addr.arpa ~76.100.in-addr.arpa
                    ~77.100.in-addr.arpa ~78.100.in-addr.arpa ~79.100.in-addr.arpa ~80.100.in-addr.arpa ~81.100.in-addr.arpa
                    ~82.100.in-addr.arpa ~83.100.in-addr.arpa ~84.100.in-addr.arpa ~85.100.in-addr.arpa ~86.100.in-addr.arpa
                    ~87.100.in-addr.arpa ~88.100.in-addr.arpa ~89.100.in-addr.arpa ~90.100.in-addr.arpa ~91.100.in-addr.arpa
                    ~92.100.in-addr.arpa ~93.100.in-addr.arpa ~94.100.in-addr.arpa ~95.100.in-addr.arpa ~96.100.in-addr.arpa
                    ~97.100.in-addr.arpa ~98.100.in-addr.arpa ~99.100.in-addr.arpa ~ts.net

Link 4 (docker0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

**Comment by bradh352** [comment] 2024-08-21 11:40
@mikaellindemann that's definitely helpful. 

I looked up vcpkg and I do see they don't include the adig or ahost binaries which is unfortunate.

I see the split dns is handled by a local resolver, systemd resolved i assume, so only a single dns server is available for use by c-ares.

The search order for your config would be: `portfolio-service.eu-central-1.compute.internal`, `portfolio-service.tailXXXXX.ts.net`, `portfolio-service`

So something isn't going right there, most likely its stopping on the first search domain, maybe because of an unexpected error code.

Any chance you'd be willing to run a tcpdump of performing the failing query?  I think  this would give me sufficient info since it should output the query and error code returned:
```
tcpdump -vvn -i lo udp port 53
```

Infact, if you can show both the working and non-working tcpdumps from the 2 versions of c-ares that would be even more helpful to see the difference. 

Once I have that, it should be easy to write a test case to reproduce and correct.

**Comment by bradh352** [comment] 2024-08-21 12:28
@mikaellindemann and just to clarify, when you said "The behaviour is the same on version 1.31.0." you mean the same as 1.33.0 (broken), not 1.28.1 (working)

**Comment by bradh352** [comment] 2024-08-21 14:29
> > @mikaellindemann and just to clarify, when you said "The behaviour is the same on version 1.31.0." you mean the same as 1.33.0 (broken), not 1.28.1 (working), right?
> 
> Sorry for the vague statement. Yes - 1.31.0 is not working for our use-case.
> 
> I will find the time to run the tcpdump test tomorrow.
> 
> Thank you for your support!

I appreciate the assistance, its hard to debug something I can't reproduce so its great you're willing to help in the investigation, thanks!

**Comment by mikaellindemann** [comment] 2024-08-22 08:48
I ran the tcpdump as suggested above:

```
# Output on 1.33.0
10:03:30.431028 IP (tos 0x0, ttl 64, id 54665, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.41839 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0xdb88!] 10586+ AAAA? portfolio-service. (35)
10:03:30.431063 IP (tos 0x0, ttl 64, id 54666, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.41839 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0x7407!] 43995+ A? portfolio-service. (35)
10:03:30.431165 IP (tos 0x0, ttl 1, id 47797, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.41839: [bad udp cksum 0xfe72 -> 0x5706!] 10586 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:03:30.431206 IP (tos 0x0, ttl 64, id 54667, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.41839 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0xdb88!] 10586+ AAAA? portfolio-service. (35)
10:03:30.431244 IP (tos 0x0, ttl 1, id 47798, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.41839: [bad udp cksum 0xfe72 -> 0xef84!] 43995 ServFail* q: A? portfolio-service. 0/0/0 (35)
10:03:30.431269 IP (tos 0x0, ttl 64, id 54668, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.41839 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0x7407!] 43995+ A? portfolio-service. (35)
10:03:30.431308 IP (tos 0x0, ttl 1, id 47799, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.41839: [bad udp cksum 0xfe72 -> 0x5706!] 10586 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:03:30.431332 IP (tos 0x0, ttl 64, id 54669, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.41839 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0xdb88!] 10586+ AAAA? portfolio-service. (35)
10:03:30.431369 IP (tos 0x0, ttl 1, id 47800, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.41839: [bad udp cksum 0xfe72 -> 0xef84!] 43995 ServFail* q: A? portfolio-service. 0/0/0 (35)
10:03:30.431393 IP (tos 0x0, ttl 64, id 54670, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.41839 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0x7407!] 43995+ A? portfolio-service. (35)
10:03:30.431429 IP (tos 0x0, ttl 1, id 47801, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.41839: [bad udp cksum 0xfe72 -> 0x5706!] 10586 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:03:30.431493 IP (tos 0x0, ttl 1, id 47802, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.41839: [bad udp cksum 0xfe72 -> 0xef84!] 43995 ServFail* q: 
```

```
# Output on 1.28.1
10:05:41.759291 IP (tos 0x0, ttl 64, id 21392, offset 0, flags [DF], proto UDP (17), length 80)
    127.0.0.1.43564 > 127.0.0.53.53: [bad udp cksum 0xfe83 -> 0xa7fc!] 55910+ AAAA? portfolio-service.tailXXXXX.ts.net. (52)
10:05:41.759326 IP (tos 0x0, ttl 64, id 21393, offset 0, flags [DF], proto UDP (17), length 80)
    127.0.0.1.43564 > 127.0.0.53.53: [bad udp cksum 0xfe83 -> 0xc35e!] 48927+ A? portfolio-service.tailXXXXX.ts.net. (52)
10:05:41.759718 IP (tos 0x0, ttl 1, id 63279, offset 0, flags [DF], proto UDP (17), length 96)
    127.0.0.53.53 > 127.0.0.1.43564: [bad udp cksum 0xfe93 -> 0xa3c1!] 48927 q: A? portfolio-service.tailXXXXX.ts.net. 1/0/0 portfolio-service.tailXXXXX.ts.net. A 100.65.120.99 (68)
10:05:41.759857 IP (tos 0x0, ttl 1, id 63280, offset 0, flags [DF], proto UDP (17), length 80)
    127.0.0.53.53 > 127.0.0.1.43564: [bad udp cksum 0xfe83 -> 0x277c!] 55910 q: AAAA? portfolio-service.tailXXXXX.ts.net. 0/0/0 (52)
10:05:41.759888 IP (tos 0x0, ttl 64, id 21394, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.43564 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0xfbbf!] 614+ AAAA? portfolio-service. (35)
10:05:41.759962 IP (tos 0x0, ttl 1, id 63281, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.43564: [bad udp cksum 0xfe72 -> 0x773d!] 614 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:05:41.759986 IP (tos 0x0, ttl 64, id 21395, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.43564 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0xfbbf!] 614+ AAAA? portfolio-service. (35)
10:05:41.760051 IP (tos 0x0, ttl 1, id 63282, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.43564: [bad udp cksum 0xfe72 -> 0x773d!] 614 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:05:41.760074 IP (tos 0x0, ttl 64, id 21396, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.43564 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0xfbbf!] 614+ AAAA? portfolio-service. (35)
10:05:41.760138 IP (tos 0x0, ttl 1, id 63283, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.43564: [bad udp cksum 0xfe72 -> 0x773d!] 614 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:05:51.531694 IP (tos 0x0, ttl 64, id 4005, offset 0, flags [DF], proto UDP (17), length 80)
    127.0.0.1.36757 > 127.0.0.53.53: [bad udp cksum 0xfe83 -> 0x4877!] 21635+ AAAA? portfolio-service.tailXXXXX.ts.net. (52)
10:05:51.531729 IP (tos 0x0, ttl 64, id 4006, offset 0, flags [DF], proto UDP (17), length 80)
    127.0.0.1.36757 > 127.0.0.53.53: [bad udp cksum 0xfe83 -> 0xed67!] 44973+ A? portfolio-service.tailXXXXX.ts.net. (52)
10:05:51.532208 IP (tos 0x0, ttl 1, id 65412, offset 0, flags [DF], proto UDP (17), length 96)
    127.0.0.53.53 > 127.0.0.1.36757: [bad udp cksum 0xfe93 -> 0xcdd4!] 44973 q: A? portfolio-service.tailXXXXX.ts.net. 1/0/0 portfolio-service.tailXXXXX.ts.net. A 100.65.120.99 (68)
10:05:51.532724 IP (tos 0x0, ttl 1, id 65413, offset 0, flags [DF], proto UDP (17), length 80)
    127.0.0.53.53 > 127.0.0.1.36757: [bad udp cksum 0xfe83 -> 0xc7f6!] 21635 q: AAAA? portfolio-service.tailXXXXX.ts.net. 0/0/0 (52)
10:05:51.532757 IP (tos 0x0, ttl 64, id 4007, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.36757 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0x1b66!] 64854+ AAAA? portfolio-service. (35)
10:05:51.532843 IP (tos 0x0, ttl 1, id 65414, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.36757: [bad udp cksum 0xfe72 -> 0x96e3!] 64854 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:05:51.532869 IP (tos 0x0, ttl 64, id 4008, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.1.36757 > 127.0.0.53.53: [bad udp cksum 0xfe72 -> 0x1b66!] 64854+ AAAA? portfolio-service. (35)
10:05:51.532946 IP (tos 0x0, ttl 1, id 65415, offset 0, flags [DF], proto UDP (17), length 63)
    127.0.0.53.53 > 127.0.0.1.36757: [bad udp cksum 0xfe72 -> 0x96e3!] 64854 ServFail* q: AAAA? portfolio-service. 0/0/0 (35)
10:05:51.532972 IP (tos 0x0, ttl 64, id 4009, offset 0, flags [DF], proto UDP (17), length 63)
```

On 1.28.1 I had to run the test a few times, before tcpdump wrote logs - probably due to some buffering of stdout.

Also - the test was run on a different machine that is not hosted in AWS, so I will put the DNS configuration outputs of that machine here as well:

```
# /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad
search tailXXXXX.ts.net
```

```bash
$ resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp68s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (enp33s0f0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (enp33s0f1)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.1
       DNS Servers: 192.168.1.1

Link 5 (wlo2)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 7 (docker0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 8 (br-b48017e8d577)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 89 (tailscale0)
    Current Scopes: DNS
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 100.100.100.100
       DNS Servers: 100.100.100.100
        DNS Domain: tailXXXXX.ts.net ~0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa ~100.100.in-addr.arpa ~101.100.in-addr.arpa ~102.100.in-addr.arpa ~103.100.in-addr.arpa ~104.100.in-addr.arpa ~105.100.in-addr.arpa ~106.100.in-addr.arpa ~107.100.in-addr.arpa ~108.100.in-addr.arpa ~109.100.in-addr.arpa ~110.100.in-addr.arpa ~111.100.in-addr.arpa
                    ~112.100.in-addr.arpa ~113.100.in-addr.arpa ~114.100.in-addr.arpa ~115.100.in-addr.arpa ~116.100.in-addr.arpa ~117.100.in-addr.arpa ~118.100.in-addr.arpa ~119.100.in-addr.arpa ~120.100.in-addr.arpa ~121.100.in-addr.arpa ~122.100.in-addr.arpa ~123.100.in-addr.arpa ~124.100.in-addr.arpa ~125.100.in-addr.arpa ~126.100.in-addr.arpa
                    ~127.100.in-addr.arpa ~64.100.in-addr.arpa ~65.100.in-addr.arpa ~66.100.in-addr.arpa ~67.100.in-addr.arpa ~68.100.in-addr.arpa ~69.100.in-addr.arpa ~70.100.in-addr.arpa ~71.100.in-addr.arpa ~72.100.in-addr.arpa ~73.100.in-addr.arpa ~74.100.in-addr.arpa ~75.100.in-addr.arpa ~76.100.in-addr.arpa ~77.100.in-addr.arpa
                    ~78.100.in-addr.arpa ~79.100.in-addr.arpa ~80.100.in-addr.arpa ~81.100.in-addr.arpa ~82.100.in-addr.arpa ~83.100.in-addr.arpa ~84.100.in-addr.arpa ~85.100.in-addr.arpa ~86.100.in-addr.arpa ~87.100.in-addr.arpa ~88.100.in-addr.arpa ~89.100.in-addr.arpa ~90.100.in-addr.arpa ~91.100.in-addr.arpa ~92.100.in-addr.arpa
                    ~93.100.in-addr.arpa ~94.100.in-addr.arpa ~95.100.in-addr.arpa ~96.100.in-addr.arpa ~97.100.in-addr.arpa ~98.100.in-addr.arpa ~99.100.in-addr.arpa ~ts.net

Link 91 (vethf08aadc)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 93 (vethe7bdf46)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

If needed I can produce a test output on the AWS server as well, but that will take me a bit more time, due to it being a production server.

**Comment by bradh352** [comment] 2024-08-22 11:29
@mikaellindemann If it reproduced the same result, that's fine, doesn't need to be in AWS.

I'm not 100% sure your tcpdump output is right though, the 1.28.1 i think might have some mixed in results with the 1.33.0.  But what this shows on the 1.33.0 output, if accurate, is 1.33.0 is somehow treating this as if you have ndots:0 specified.  Then in addition, systemd resolved is returning SERVFAIL instead of NXDOMAIN.

In your options line in /etc/resolv.conf does it magically work if you set `ndots:1`?  

I'm going to configure an environment with systemd resolved to see if I can test and reproduce.

**Comment by bradh352** [comment] 2024-08-23 00:19
@mikaellindemann

I filed a ticket https://github.com/systemd/systemd/issues/34101 with systemd about the issue.  I'm not sure yet if it makes sense to attempt to detect this particular condition to work around a systemd bug.

I'm pretty sure PR #862 should fix your particular issue, but there's another issue that may impact other users.

In a way its good that systemd had this issue as if they didn't it would have been silently ignored that the ndots config for linux was defaulting to 0, not sure when we would have noticed that... now there's at least a test case to catch this.

@egtvedt likely this will resolve your issue as well I'm guessing.

I'll probably get a 1.33.1 release out tomorrow for this and a couple other items that have cropped up since the last release.

**Comment by egtvedt** [comment] 2024-08-23 07:49
@bradh352 thank you for pinging me. Work tasks after summer returned faster than anticipated, so I couldn't get this prioritized.

I'll upgrade to c-ares 1.33.1 and give it a test run.

**Closed** 2024-08-23 13:19 UTC
