### ISSUE TITLE
swrite failed in IOS14 if user reject or disable local network permission

### ISSUE THREAD

**Issue by jasekidd** [c-ares/c-ares#412] opened 2021-08-05 07:41 UTC
In IOS14 device, if user reject or disable local network permission in App permission setting.
c-ares  will get code 65 after  calling swrite, as shown below:

![1](https://user-images.githubusercontent.com/38203531/128310045-06d78163-64ab-4bb5-8d63-f2ca0dadeb15.png)

What we find is that when calling  code "int nscount = res_getservers(&res, addr, MAXNS);"  in ares_init.c
The returned dns svr's sockaddr is LAN ip like "192.168.**.**".
If user reject local network permission, this LAN ip can not read or write any more.
Here is the similar problem:
https://developer.apple.com/forums/thread/661606

**Comment by bradh352** [comment] 2021-08-05 11:47
Can you clarify what you would consider the expected behavior if the user disables the network permission?

**Comment by bradh352** [comment] 2021-08-12 16:21
Described behavior summary:
 * When a user disables network permissions on ios for the application using c-ares, c-ares returns an error code as it has lost network access

As far as I can tell, this is expected behavior as c-ares cannot break out of the ios sandbox to regain network access (nor should it attempt to).

Closing this ticket as the reporting user has not described why they see this as being wrong.

**Closed by bradh352** 2021-08-12 16:21 UTC

**Comment by yifzone** [comment] 2022-05-19 09:57
I had the same problem, i use c-ares with libcurl in ios, i allways get resolve host failed when reject local network permission(system version greater than ios14, because local network permission is an new permission after ios14).
I did a lot test, finally, found in wifi and dns is 192.168.x.x, this error happend 100%.
I guess the reason was c-ares can't communication with dns servers like 192.168.x.x when reject local network permission???
Does any one have solution？？
