### ISSUE TITLE
ares_set_servers_ports_csv doesn't work with IPv6?

### ISSUE THREAD

**Issue by Hsilgos** [c-ares/c-ares#543] opened 2023-08-20 15:48 UTC
Hi,

I'm trying to specify custom IPv6 DNS with CURL on Android. There is no documentation about support of IPv6 so I started to dig.
CURL calls function `ares_set_servers_ports_csv` which calls `set_servers_csv` [where doc says](https://github.com/c-ares/c-ares/blob/main/src/lib/ares_options.c#L252):
```
/* IPv6 addresses with ports require square brackets [fe80::1%lo0]:53 */
```
I tried Google public IPv6 using the following representation: `2001:4860:4860::8888%wlan0`, `[2001:4860:4860::8888%wlan0]`, `[2001:4860:4860::8888%wlan0]:53`, `2001:4860:4860::8888`, `[2001:4860:4860::8888]`, `[2001:4860:4860::8888]:53` and full forms without success. 
Forms without interface like `2001:4860:4860::8888` is timed out.
Digging farther I see that IPv6 is parsed with `ares_inet_pton6` [here](https://github.com/c-ares/c-ares/blob/main/src/lib/inet_net_pton.c#L221) which doesn't process symbol `%` so despite the documentation for `set_servers_csv` I can't specify interface.

So C-Ares seems doesn't support IPv6 for custom DNS? Is it Android specific problem may be?

**Comment by bradh352** [comment] 2023-08-20 16:24
I can tell you c-ares definitely does not support the %interface syntax.  The comment in the code is definitely wrong there, I'm not sure why its there.  That said, I can't find in the *documentation* where it ever suggests c-ares supports the %interface syntax.  Can you point me to this documentation you're referencing?

You shouldn't need to specify an interface for ipv6, the system routes will handle that automatically and will automatically choose the most proper source ip address based on the destination.  The %interface syntax is really a highly specialized case and should not be generally used.

**Comment by Hsilgos** [comment] 2023-08-20 16:50
> Can you point me to this documentation you're referencing?

I mentioned the proper place in my question: https://github.com/c-ares/c-ares/blob/main/src/lib/ares_options.c#L252
This is short doc for `set_servers_csv `

> You shouldn't need to specify an interface for ipv6, the system routes will handle that automatically and will automatically choose the most proper source ip address based on the destination. The %interface syntax is really a highly specialized case and should not be generally used.

Well, on Android on some devices I have to specify interface when I use CURL with Proxy. I thought with C-Ares it can be the case. 

In any case when I specify `2001:4860:4860::8888` it's timed out. Not sure what is the reason: Android emulator, local network environment, C-Ares, DNS server is offline or something else.

**Comment by bradh352** [comment] 2023-08-20 20:39
Alright, good, no documentation states that, just a bad comment in the code.

I'm not sure why you wouldn't get DNS responses, that's something you'd need to employ some sort of network trace to evaluate.  I doubt it has anything to do with needing the %interface.  I'm also not entirely sure how a proxy would matter in that regard since the proxy would be doing its own DNS resolution internally.

**Comment by Hsilgos** [comment] 2023-08-20 22:40
> Alright, good, no documentation states that, just a bad comment in the code.

Yeah, comment in code. The problem is that official public c-ares documentation describes only IPv4 adresses. CURL's documentation is just copypaste of c-ares.

Proxy has nothing with c-ares.
I mentioned Proxy because on Android in CURL I have to specify interface for IPv6, otherwise it's simply not working. So I thought that for c-ares I also should do it

**Comment by bradh352** [comment] 2023-11-01 22:47
Since the function does indeed take ipv6 addresses properly, and just doesn't support %iface syntax, I'm closing as duplicate of #462

**Closed by bradh352** 2023-11-01 22:47 UTC
