### ISSUE TITLE
UDP connect for every DNS query

### ISSUE THREAD

**Issue by rakeshdatta** [c-ares/c-ares#539] opened 2023-08-03 16:31 UTC
Hello,
My setup is using envoy->k8s->coredns.

I am facing this https://github.com/envoyproxy/envoy/issues/7965 I think. One suggested solution is to use DNS over TCP option. However, we want to stick with udp. 

- In nginx, when we had a similar issue, and we fixed it by changing send() calls, to send_to() calls. We provided a flag, which when enabled, the fix would be used. Meaning, with the fix. for every DNS query, we essentially force consult the kube-proxy, and we do not land on a faulty/dead coredns endpoint. I am assuming, we are using send() calls underneath. Wondering, can we implement a similar feature in c'ares? 

- Also, another question would be, if the coredns is overloaded (not dead) and the dns requests are timing out, DNS over TCP really help? Or is there another solution?

**Comment by bradh352** [comment] 2023-08-03 21:41
It sounds like you want to force a new ephemeral port to be used on every DNS request.  There is no current option for that in c-ares.

**Comment by rakeshdatta** [comment] 2023-08-04 03:54
Thats right @bradh352 . I am proposing that as an enhancement behind a configurable flag. This would act as a solution for https://github.com/envoyproxy/envoy/issues/7965, an alternate to moving to DNS over TCP. Do u see this reasonable?

**Comment by bradh352** [comment] 2023-08-05 18:45
I'm going to close this as a duplicate of #444

**Closed by bradh352** 2023-08-05 18:45 UTC
