### ISSUE TITLE
thirdparty/apple/dnsinfo.h is not in the release tarballs

### ISSUE THREAD

**Issue by jblazquez** [c-ares/c-ares#771] opened 2024-05-28 23:39 UTC
[This file](https://github.com/c-ares/c-ares/blob/main/src/lib/thirdparty/apple/dnsinfo.h) is not in [this tarball](https://github.com/c-ares/c-ares/releases/download/cares-1_29_0/c-ares-1.29.0.tar.gz), so compilation of `ares_sysconfig_mac.c` fails.

**Comment by dfandrich** [comment] 2024-05-29 00:47
Duplicate of #763.

**Closed by dfandrich** 2024-05-29 00:47 UTC
