### ISSUE TITLE
1.29.0 Does not build on macOS

### ISSUE THREAD

**Issue by debohman** [c-ares/c-ares#766] opened 2024-05-24 19:48 UTC
```
ares_sysconfig_mac.c:54:12: fatal error: 'thirdparty/apple/dnsinfo.h' file not found
   54 | #  include "thirdparty/apple/dnsinfo.h"
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

That header file does not appear to be anywhere in the distribution.

```
% find . -type f -name dnsinfo.h
% 
```

**Comment by bradh352** [comment] 2024-05-24 20:23
duplicate of #763

**Closed by bradh352** 2024-05-24 20:23 UTC
