### ISSUE TITLE
Issue with release v1.27.0 CMake

### ISSUE THREAD

**Issue by wmorgan6796** [c-ares/c-ares#720] opened 2024-03-01 00:23 UTC
Hi,

I'm getting this following error when pulling c-ares via CMake `FetchContent`

```
CMake Error at cmake-build-local-debug/_deps/c-ares-src/src/lib/CMakeLists.txt:87 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES called with incorrect number of arguments.
```

this points to this area of code: https://github.com/c-ares/c-ares/blame/main/src/lib/CMakeLists.txt#L87-L93 

which seems to have added  `C_STANDARD 90` to the SET_TARGET_PROPERTIES call in the past few months.

Environment: GCC 13.2, CMake 3.27.1

Not sure why its broken, but wanted to file this quickly to see if anyone else had similar issues. I'll continue to look into this and hopefully find the root cause.

**Comment by bradh352** [comment] 2024-03-01 02:14
Looks like this is a chain building issue, so that means it is likely https://github.com/c-ares/c-ares/commit/52ad1246767d3f627f0f9769c1af15d6dd25f3c7 is the cause.

I'm guessing the variable CMAKE_RUNTIME_OUTPUT_DIRECTORY is not set, therefore leading to the wrong number of arguments issue.

According to the docs, I'm thinking that variable should be RUNTIME_OUTPUT_DIRECTORY instead, as the CMAKE_ variant is for overriding a default.

**Comment by bradh352** [comment] 2024-03-01 11:28
pretty sure this is fixed in d322313

**Closed** 2024-03-01 11:33 UTC

**Comment by wmorgan6796** [comment] 2024-03-01 14:20
@bradh352 would it be possibly to cut a bugfix release for this? My team is looking to update c-ares, but can only use official releases.

**Comment by bradh352** [comment] 2024-03-01 16:03
We need to for a packaging issue in 1.27.0 anyhow (missing 3 manpages), but I'm pretty sure @bagder is out on vacation for a week or so, and we use his GPG signing key for releases.  So I'm really not sure when it can happen.

**Comment by wmorgan6796** [comment] 2024-03-01 17:04
That’s good for me. I’ve checked the fix and it works correctly now. 

Thanks for the rapid fix.
