### ISSUE TITLE
On PF_UNSPEC, skip retry on second address class if we have a reply on one

### ISSUE THREAD

**Issue by sachusachin622** [c-ares/c-ares#541] opened 2023-08-11 07:06 UTC
Hi,

**I am using curl 8.2.1 with c-ares 1.19.0**

The issue I am noticing with c-ares is, when we don't specify the ip address to query for a domain name using the curl command and there is a timeout associated to it the resolution fails for the domain and curl as a consequence also fails.

root@2d142b34d5a2:/# curl -m20 -v http://www.google.com
* processing: http://www.google.com
06:57:00.807787 IP 2d142b34d5a2.60042 > 10.174.75.167.domain: 29950+ A? www.google.com. (32)
06:57:00.807844 IP 2d142b34d5a2.60042 > 10.174.75.167.domain: 43180+ AAAA? www.google.com. (32)
06:57:00.808314 IP 2d142b34d5a2.47661 > 10.174.75.167.domain: 8116+ PTR? 167.75.174.10.in-addr.arpa. (44)
06:57:00.808714 IP 10.174.75.167.domain > 2d142b34d5a2.60042: 29950* 1/0/0 A 142.250.195.228 (49)
06:57:00.809018 IP 10.174.75.167.domain > 2d142b34d5a2.60042: 29950* 1/0/0 A 142.250.195.228 (49)
06:57:05.809237 IP 2d142b34d5a2.60042 > 10.174.75.167.domain: 43180+ AAAA? www.google.com. (32)
06:57:05.813398 IP 2d142b34d5a2.47661 > 10.174.75.167.domain: 8116+ PTR? 167.75.174.10.in-addr.arpa. (44)
06:57:15.811191 IP 2d142b34d5a2.60042 > 10.174.75.167.domain: 43180+ AAAA? www.google.com. (32)
* Resolving timed out after 20001 milliseconds
* Closing connection
curl: (28) Resolving timed out after 20001 milliseconds
root@2d142b34d5a2:/# 

If we don't pass the timeout for resolving the domain the curl passes by using the ipv4 address. But this generally take a long time to timeout and use the ipv4 address. In my testing its over a minute always before returning with the resolved address. Some program using curl generally doesn't wait so long. So is it possible to send the partial query response back to curl before it time's out, so that it can use the ipv4 address at least and continue with its operations?

My test environment is ubuntu 16.04

Thanks

**Comment by bradh352** [comment] 2023-08-11 11:42
likely curl should be setting more aggressive timers for ARES_OPT_TIMEOUTMS (default is 5000 which even with geostationary satellite latency is way too high these days, and that is per attempt not overall), and possibly even reduce the number of retries via ARES_OPT_TRIES (default is 4, and that's per dns server not overall).

I could see it being a reasonable request, however, to stop retries if we at least have results for one address class.   Its fairly unusual, however, for the same DNS server to just not respond at all to one address class request but to respond to the other.  Do you know why this is happening?

**Comment by sachusachin622** [comment] 2023-08-17 06:28
hi ,
I am not sure why it is happening, I am just trying with curl with -m20 seconds options so that after 20seconds its failing.

You changed this one to **Feature Request** Is there any timeline for this feature, Can you please tell me the timeline.

Thanks,
Sachin

**Comment by bradh352** [comment] 2023-08-28 14:12
I changed the default values in c-ares main.  I'll fix this before the next release, in the case where we have one address class response, we shouldn't retry other address classes, just return what we have.

**Comment by bagder** [comment] 2023-08-28 14:19
> we shouldn't retry other address classes, just return what we have.

Ah yes, that's the key I believe to make @sachusachin622's use case act nicer.

**Comment by sachusachin622** [comment] 2023-08-29 05:35
Hi @bagder @bradh352 ,
I get what you are saying we will immediately return ipv4 or ipv6 address and not wait for the failed query. 
I have one small edge case i just want to discuss am sure its very unlikely but i want to get your opinion on it 
let's say CURL sets timeout of 10 using -m option
now what i believe will happen is, the query will be sent out after 2 seconds + 4 seconds after the 2 seconds is completed + 8 seconds after the 6 seconds completed. this is the total of 14 seconds of c-ares to return
But curl still timeout after 10 seconds which means we will miss 1 query to the DNS server which could produce a positive result.
I am asking this question because i feel there should be a relation between the -m option and the retries intervals that C-ares uses.

Thanks

**Comment by bagder** [comment] 2023-08-29 06:23
> I am asking this question because i feel there should be a relation between the -m option and the retries intervals that C-ares uses.

(this is more a curl question than a c-ares one I believe, but...)

How? 

I think c-ares should have sensible defaults for name resolving in lots of environments.

When a user restricts how long they want to allow curl to run, they rarely know or even think about how large portion of that time they would like to "waste" on name resolving before they give up. I would actually expect most users  to presume that the name resolution process is the same with the same timeouts and number of retries etc.

If you want all the DNS timeouts and retries, then you simply don't set a very short timeout.

**Comment by bradh352** [comment] 2023-08-29 11:10
Messing with per-attempt timeouts isn't going to be the best way to handle things, as you could end up being too aggressive and not legitimately wait long enough for a response before giving up and trying the next server.  When a timeout occurs it stops waiting on a response completely for that attempt and starts a new attempt against the next server.

You probably want #135 implemented to limit the maximum overall time per query, which is independent of the per-attempt timeout.  curl would then want to implement setting that option.  #135 is on my list of todo items before the next c-ares release.

**Comment by sachusachin622** [comment] 2023-08-31 06:28
> I changed the default values in c-ares main. I'll fix this before the next release, in the case where we have one address class response, we shouldn't retry other address classes, just return what we have.

hi @bradh352 ,

Here, we anticipate the return of a single address class response. Two scenarios come to mind:

1. In the first scenario, if a single server is present, and we encounter a PF_UNSPEC case, the system will initiate queries for both IPv4 and IPv6 address classes. If the IPv4 query passes, it will immediately return the IPv4 address.

2. In the second scenario, assuming the existence of two servers—S1 and S2—when encountering the PF_UNSPEC case, the system will initiate queries for both IPv4 and IPv6 address classes. If the IPv4 query is successful but the IPv6 query fails with S1 server, we will proceed by either retrying the IPv6 query with S2 server or return the available IPv4 address ?

If the response yields an IPv4 address without attempting to fetch an IPv6 address from the second server, I will try to implement this.

Thanks

**Comment by bradh352** [comment] 2023-09-25 23:32
@sachusachin622 if you can test that PR #551 with your usecase, that would be helpful to confirm it works as intended

**Comment by bradh352** [comment] 2023-09-26 14:42
Fixed in #551

**Closed by bradh352** 2023-09-26 14:42 UTC
Labels: Feature Request
