### ISSUE TITLE
Warnings from `ranlib` on macOS

### ISSUE THREAD

**Issue by timwoj** [c-ares/c-ares#446] opened 2021-11-30 22:36 UTC
OS Version: macOS 11.6
Compiler version: Apple clang version 13.0.0 (clang-1300.0.29.3)

This is on the current commit on master. Linking calls `ar`, which calls `ranlib`, which then spits out these warnings:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_android.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_getenv.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_platform.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_strcasecmp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_writev.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-windows_port.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_android.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_getenv.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_platform.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_strcasecmp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-ares_writev.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libcares.a(libcares_la-windows_port.o) has no symbols
```

It does this on both autotools and cmake builds. It seems like some of those files shouldn't be included at all during a macOS build (like the android and windows ones), but I get using `#ifdef` guards instead of making the build system exclude them entirely.

**Comment by bradh352** [comment] 2021-11-30 22:38
This won't be fixed.  The problem is the build system policy within c-ares that all systems share Makefile.inc which includes all possible source files and its not possible to conditionalize file inclusion based on the system due to this practice.

**Closed by bradh352** 2021-11-30 22:38 UTC

**Comment by timwoj** [comment] 2021-11-30 22:44
> The problem is the build system policy within c-ares that all systems share Makefile.inc which includes all possible source files and its not possible to conditionalize file inclusion based on the system due to this practice.

Gotcha, that makes perfect sense.

That said, there is an argument that can be passed to `ranlib` on macOS that causes it to not warn on empty files. It requires modifying the arguments to `ar` as well, and I don't know the build setup for c-ares well enough to know the best place to do it. The argument is `-no_warning_for_no_symbols`.

**Comment by bradh352** [comment] 2021-11-30 22:46
We'd accept patches for silencing warnings like that ... though they'd have to make sure they don't mess up any other OS.  The ranlib and ar calls we don't invoke manually, its done internally by autotools and cmake respectively.
